services:
  adlab_db:
    image: postgres:latest
    container_name: adlab-db-container
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - adlab_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis_db:
    image: redis:7
    container_name: scheduler-cache-container
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  adlab_api:
   # image: ghcr.io/americelt-org/americelt-adlab-api:latest
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: adlab-api-container
    ports:
      - "${PORT}:${PORT}"
    volumes: 
      - ./src:/app/src
    env_file:
    - .env
    depends_on:
      adlab_db:
        condition: service_healthy
      redis_db:
        condition: service_healthy

volumes:
  adlab_data:
  redis_data:
