services:
  postgres_db:
    image: postgres:latest
    container_name: adlab-db-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: postgres1234
      POSTGRES_DB: adlab_db
    volumes:
      - postgresdb_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "adlab_db"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 30s


  redis_db:
    image: redis:7
    container_name: scheduler-cache-container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adlab-api-container
    ports: 
      - '3001:3001'
    volumes: 
      - ./src:/app/src
    env_file:
    - .env
    depends_on:
      postgres_db:
        condition: service_healthy
      redis_db:
        condition: service_healthy

volumes:
  postgresdb_data:
  redis_data:
